import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { PublicFooter, PublicNav } from "@/components/PublicChrome"
import { getArticle, resourceArticles } from "@/lib/resources"

type ArticlePageProps = {
  params: Promise<{
    slug: string
  }>
}

export function generateStaticParams() {
  return resourceArticles.map((article) => ({ slug: article.slug }))
}

export async function generateMetadata({
  params,
}: ArticlePageProps): Promise<Metadata> {
  const { slug } = await params
  const article = getArticle(slug)
  if (!article) {
    return { title: "Article not found" }
  }
  const canonical = `/blog/${article.slug}`
  // Dynamic OG image generated by /api/og (next/og); each post gets
  // its own preview card with the post's title + category.
  const ogImage = `/api/og?title=${encodeURIComponent(article.title)}&category=${encodeURIComponent(article.category)}`
  return {
    title: article.title,
    description: article.summary,
    alternates: { canonical },
    openGraph: {
      type: "article",
      title: article.title,
      description: article.summary,
      url: canonical,
      images: [{ url: ogImage, width: 1200, height: 630, alt: article.title }],
    },
    twitter: {
      card: "summary_large_image",
      title: article.title,
      description: article.summary,
      images: [ogImage],
    },
  }
}

export default async function ArticlePage({ params }: ArticlePageProps) {
  const { slug } = await params
  const article = getArticle(slug)

  if (!article) notFound()

  return (
    <div className="page-shell">
      <PublicNav />
      <main>
        <article className="article-page">
          <div className="container">
            <Link className="button-ghost" href="/blog">
              Back to resources
            </Link>
            <span className="section-kicker">{article.category}</span>
            <h1>{article.title}</h1>
            <p>{article.summary}</p>
            <small>{article.readingTime}</small>
            <div className="article-body">
              {article.sections.map((section) => (
                <section key={section.title}>
                  <h2>{section.title}</h2>
                  <p>{section.body}</p>
                </section>
              ))}
            </div>
          </div>
        </article>
      </main>
      <PublicFooter />
    </div>
  )
}
